export const ACHIEVEMENTS_LIST = [
    { id: 0, icon: '🎓', title: 'Primeiros Passos', desc: 'Termine o tutorial.' },
    { id: 1, icon: '🌲', title: 'Primeira Madeira', desc: 'Você coletou madeira e iniciou a jornada.' },
    { id: 2, icon: '⛏️', title: 'Idade da Pedra', desc: 'Você conseguiu sua primeira pedra.' },
    { id: 3, icon: '🧟', title: 'Primeiro Sangue', desc: 'Derrote o primeiro zumbi.' },
    { id: 4, icon: '🔥', title: 'Aquecendo', desc: 'Crie ou encontre calor (colete carvão ou lenha).' },
    { id: 5, icon: '🍖', title: 'Caçador Básico', desc: 'Consiga sua primeira comida crua.' },
    { id: 6, icon: '🍳', title: 'Cozinheiro', desc: 'Cozinhe algo na fornalha.' },
    { id: 7, icon: '💎', title: 'Diamante!', desc: 'Encontre e minere um diamante.' },
    { id: 8, icon: '🏊', title: 'Mergulhador', desc: 'Você nadou pela primeira vez.' },
    { id: 9, icon: '🦇', title: 'Morcegos Ocultos', desc: 'Descubra a primeira caverna profunda.' },
    { id: 10, icon: '👑', title: 'O Chefe Cayu', desc: 'Derrote o primeiro Boss.' },
    { id: 11, icon: '⚔️', title: 'Caçador de Monstros', desc: 'Mate 100 monstros.' },
    { id: 12, icon: '🏁', title: 'Zerou o jogo!', desc: 'Sobreviva 100 dias (ou vença o boss final).' },
    { id: 13, icon: '🍎', title: 'Agricultor', desc: 'Crie uma plantação e colha algo.' },
    { id: 14, icon: '🐮', title: 'Fazendeiro', desc: 'Mantenha animais por perto.' },
    { id: 15, icon: '🧪', title: 'O Químico', desc: 'Faça a primeira poção ou itém químico.' },
    { id: 16, icon: '🛏️', title: 'Bons Sonhos', desc: 'Durma em uma cama pela primeira vez.' },
    { id: 17, icon: '🏹', title: 'Arqueiro', desc: 'Crie e use um arco.' },
    { id: 18, icon: '🏡', title: 'Lar Doce Lar', desc: 'Construa sua primeira casa fechada.' },
    { id: 19, icon: '🎣', title: 'Pescador', desc: 'Pesque um peixe.' },
    { id: 20, icon: '☠️', title: 'Sorte Ruim', desc: 'Morra pela primeira vez.' },
    { id: 21, icon: '💀', title: 'Matador de Esqueletos', desc: 'Derrote 50 esqueletos.' },
    { id: 22, icon: '🕷️', title: 'Aracnofobia', desc: 'Derrote uma aranha venenosa.' },
    { id: 23, icon: '🛡️', title: 'Defesa Focada', desc: 'Crie um escudo.' },
    { id: 24, icon: '🗡️', title: 'Lâmina de Ferro', desc: 'Faça uma espada de ferro.' },
    { id: 25, icon: '🧙', title: 'Mago Iniciante', desc: 'Encontre um livro mágico.' },
    { id: 26, icon: '🌍', title: 'Explorador', desc: 'Caminhe mil blocos de distância.' },
    { id: 27, icon: '🏜️', title: 'Areia Quente', desc: 'Sobreviva no deserto.' },
    { id: 28, icon: '❄️', title: 'Frio Congelante', desc: 'Encontre o bioma de neve.' },
    { id: 29, icon: '🌲', title: 'Lenhador', desc: 'Corte 100 árvores.' },
    { id: 30, icon: '⛏️', title: 'Mineiro Profissional', desc: 'Minere 1000 blocos de pedra.' },
    { id: 31, icon: '💼', title: 'Mochila Cheia', desc: 'Preencha todos os espaços do inventário.' },
    { id: 32, icon: '🧥', title: 'Bem Vestido', desc: 'Equipe o conjunto completo de armadura de couro.' },
    { id: 33, icon: '🔗', title: 'Cavaleiro', desc: 'Equipe armadura de ferro completa.' },
    { id: 34, icon: '💎', title: 'Bilionário', desc: 'Equipe armadura de diamante completa.' },
    { id: 35, icon: '💥', title: 'Bum!', desc: 'Faça um creeper/zumbi explosivo detonar.' },
    { id: 36, icon: '🍎', title: 'Maçã Dourada', desc: 'Coma a maçã mística.' },
    { id: 37, icon: '🎶', title: 'DJ', desc: 'Toque um disco em uma Jukebox.' },
    { id: 38, icon: '🐶', title: 'Melhor Amigo', desc: 'Domestique um lobo.' },
    { id: 39, icon: '🐱', title: 'Dono de Gato', desc: 'Domestique um gato (se adicionado amanhã).' },
    { id: 40, icon: '🐎', title: 'Cowboy', desc: 'Monte em um cavalo.' },
    { id: 41, icon: '🐐', title: 'Escalador', desc: 'Suba até a altura máxima.' },
    { id: 42, icon: '⛏️', title: 'Fundo do Poço', desc: 'Chegue na Rocha Matriz (Bedrock).' },
    { id: 43, icon: '🚪', title: 'Bem Vindo', desc: 'Coloque uma porta.' },
    { id: 44, icon: '🪨', title: 'Pedregulho', desc: 'Faça um abrigo inteiro de pedra pura.' },
    { id: 45, icon: '🌵', title: 'Dano Espinhadinho', desc: 'Se machuque encostando num cacto.' },
    { id: 46, icon: '☢️', title: 'Radiação', desc: 'Traga Urânio para perto.' },
    { id: 47, icon: '🟢', title: 'Proteção Bio', desc: 'Use uma roupa Hazmat.' },
    { id: 48, icon: '🌌', title: 'O Vácuo', desc: 'Tente cair no infinito.' },
    { id: 49, icon: '🌟', title: 'Meteorito?', desc: 'Encontre minério de Titânio.' },
    { id: 50, icon: '🛡️', title: 'Impiedoso', desc: 'Vença 5 hordas da noite de sangue.' },
    { id: 51, icon: '🧪', title: 'Zumbi Tóxico', desc: 'Mate um zumbi gotejando veneno.' },
    { id: 52, icon: '🩸', title: 'Noite Vermelha', desc: 'Sobreviva a primeira Lua de Sangue.' },
    { id: 53, icon: '⚒️', title: 'Mecânico', desc: 'Construa 5 fornalhas e use todas.' },
    { id: 54, icon: '📦', title: 'Acumulador', desc: 'Faça e coloque 10 baús.' },
    { id: 55, icon: '🔦', title: 'Haja Luz', desc: 'Coloque 100 tochas.' },
    { id: 56, icon: '🪓', title: 'Machado Mágico', desc: 'Consiga algo que bata mais rápido que sua mão.' },
    { id: 57, icon: '🎯', title: 'Sniper', desc: 'Atire com arco a longa distância e acerte.' },
    { id: 58, icon: '🪙', title: 'Comerciante', desc: 'Ache a moeda ou esmeralda perdida.' },
    { id: 59, icon: '🛠️', title: 'Faz Tudo', desc: 'Crie uma de cada ferramenta básica.' },
    { id: 60, icon: '⚔️', title: 'Mais Forte', desc: 'Evolua a Força até o máximo no Painel.' },
    { id: 61, icon: '🏃', title: 'Maratonista', desc: 'Corra, consumindo toda a Stamina.' },
    { id: 62, icon: '🥩', title: 'Bucho Cheio', desc: 'Fique de barriga cheia no nível 10.' },
    { id: 63, icon: '🥗', title: 'Vegetariano', desc: 'Fique 3 dias sem comer carne.' },
    { id: 64, icon: '🪦', title: 'Cemitério', desc: 'Visite a lápide da sua morte.' },
    { id: 65, icon: '⚡', title: 'Sobrecarga', desc: 'Energize a máquina de urânio.' },
    { id: 66, icon: '🔧', title: 'Upgrade', desc: 'Faça o upgrade da sua picareta de ferro.' },
    { id: 67, icon: '🧭', title: 'Perdido', desc: 'Morra e respawne longe de casa.' },
    { id: 68, icon: '👽', title: 'Easter Egg', desc: 'Descubra a mensagem escondida.' },
    { id: 69, icon: '🏆', title: 'Platina', desc: 'Conquiste as outras 68 conquistas misteriosas.' }
];
